server:
  port: 10001
spring:
  boot:
    admin:
      client:
        url: http://localhost:8769 #指定注册地址 , Spring Boot Admin Server地址
  redis: # 配置redis
    host: 192.168.139.139
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # SpringBoot默认数据源HikariCP，最大优点快；如果希望使用Druid，进行如下整合
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
mybatis:
  type-aliases-package: com.atguigu.pojo
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 对外暴露的访问入口 , 默认是/health和/info
  #      base-path: /monitor # 默认是actuator
  endpoint:
    health:
      show-details: always    # 显示所有健康状态
  server:
    port: 9999