#系统项带提示
#系统项位置spring-configuration-metadata.json
server:
  port: 8080
  servlet:
    context-path: /springboot
#  配置文件读取顺序
#  <includes>
#  <include>**/application*.yml</include>
#  <include>**/application*.yaml</include>
#  <include>**/application*.properties</include>
#  </includes>

#自定义的配置项
spring:
  jdbc:
    datasource:
      driverClassName: com.mysql.jdbc.Driver4
      url: jdbc:mysql:///springboot4
      username: root4
      password: root4

#字面量
empno: 7839
ename: SMITH
hiredate: 1982-12-13
sal: 3000.0
ismgr: false

#对象
#缩进样式
emp:
  empno: 7839
  ename: SMITH
  hiredate: 1982-12-13
  sal: 3000.0
  ismgr: false
#行内样式
emp2: { empno: 7839,ename: SMITH,hiredate: 1982-12-13,sal: 3000.0,ismgr: false }

#数组
hobby:
  - sport
  - music
  - art
  - java
#缩进样式
city:
  - beijing
  - tianjin
  - shanghai
  - chongqing
# 行内方式
hobbyArr: [ game,program,travel ]